export enum FilterOperatorsEnum {
  CONTAINS = 'contains',
  DOES_NOT_CONTAINS = 'doesnotcontain',
  EQUAL = 'eq',
  NOT_EQUAL = 'neq',
  STARTS_WITH = 'startswith',
  ENDS_WITH = 'endswith',
  IS_NULL = 'isnull',
  IS_NOT_NULL = 'isnotnull',
  IS_EMPTY = 'isempty',
  IS_NOT_EMPTY = 'isnotempty',
  GREATER_THEN = 'gt',
  GREATER_OR_EQUAL_THEN = 'gte',
  LESS_THEN = 'lt',
  LESS_OR_EQUAL_THEN = 'lte',
}
